version: "3.2"

services:
  postgres:
    image: postgres:10.8
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "reverb_orm"
      POSTGRES_PASSWORD: "reverb_orm" 
      POSTGRES_DB: "reverb_orm"