name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: ["v1.2.1"]
    name: Deno ${{ matrix.deno }}

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "reverb_orm"
          POSTGRES_PASSWORD: "reverb_orm" 
          POSTGRES_DB: "reverb_orm"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Check format
        run: |
          deno fmt --check
      - name: Test
        run: |
          deno test -c tsconfig.json --allow-net --allow-env